### ISSUE TITLE
syncnet

### ISSUE THREAD

**Issue by einsqing** [monk-after-90s/wav2lip_data_preprocess#1]
建议使用 ffmpeg ，检测出 syncnet offset，然后做一下同步处理

**Comment by monk-after-90s** [comment]
> 建议使用 ffmpeg ，检测出 syncnet offset，然后做一下同步处理

来个合并请求🤣

**Comment by SakuraMaiii** [comment]
> 建议使用 ffmpeg ，检测出 syncnet offset，然后做一下同步处理

请问如何使用ffmpeg做同步处理吗，求指导谢谢

**Comment by SakuraMaiii** [comment]
> 建议使用 ffmpeg ，检测出 syncnet offset，然后做一下同步处理

哥，求指点一下，谢谢
